[project]
name = "jury_training_course"
version = "0.1.0"
dependencies = [
    "ruamel.yaml",
    "requests",
]

[project.scripts]
setup_sio2jail = "sio2jail.setup_sio2jail:setup_sio2jail"

create_package = "commands.package:command_create_package"
make_package = "commands.package:command_create_package"
delete_package = "commands.package:command_delete_package"

prepare_makefile = "commands.prepare_makefile:command_prepare_makefile"

generate = "commands.generate:command_generate_tests"
generate_tests = "commands.generate:command_generate_tests"

delete_tests = "commands.generate:command_delete_tests"
clean_tests = "commands.generate:command_delete_tests"

verify_tests = "commands.in_ver:command_verify_tests"
inver = "commands.in_ver:command_verify_tests"

run_tests = "commands.run:command_run_tests"

check_model = "commands.run:check_model_command"

verify_package = "commands.verify:command_internal_verify_package"

generate_testcase_outputs = "commands.run:generate_testcase_outputs_command"

judge_init = "commands.judge:judge_init_command"

[tool.setuptools]
package-dir = {"" = "src"}